export const fallbackMeals = [
  {
    _id: 'meal-1',
    foodName: 'Garden Harvest Salad',
    foodImage: 'https://images.unsplash.com/photo-1543353071-873f17a7a088?auto=format&fit=crop&w=1200&q=80',
    rating: 4.7,
    category: 'Salad',
    price: 16,
    estimatedDeliveryTime: 20,
    chefName: 'Chef Anya',
    deliveryArea: 'City Market',
    chefExperience: 7,
    ingredients: ['Mixed greens', 'Heirloom tomatoes', 'Goat cheese', 'Lemon vinaigrette'],
    chefId: 'chef-1',
  },
  {
    _id: 'meal-2',
    foodName: 'Rustic Herb Chicken',
    foodImage: 'https://images.unsplash.com/photo-1604908177521-0f8dff3aef0a?auto=format&fit=crop&w=1200&q=80',
    rating: 4.9,
    category: 'Main',
    price: 28,
    estimatedDeliveryTime: 30,
    chefName: 'Chef Mateo',
    deliveryArea: 'Harbor District',
    chefExperience: 10,
    ingredients: ['Free-range chicken', 'Rosemary', 'Garlic', 'Roasted potatoes'],
    chefId: 'chef-2',
  },
  {
    _id: 'meal-3',
    foodName: 'Pan-Seared Salmon',
    foodImage: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=1200&q=80',
    rating: 4.8,
    category: 'Seafood',
    price: 32,
    estimatedDeliveryTime: 25,
    chefName: 'Chef Lina',
    deliveryArea: 'Waterfront',
    chefExperience: 8,
    ingredients: ['Wild salmon', 'Citrus glaze', 'Asparagus', 'Quinoa'],
    chefId: 'chef-3',
  },
];

export const fallbackReviews = [
  {
    _id: 'review-1',
    mealId: 'meal-3',
    reviewerName: 'Ava M.',
    userEmail: 'ava@example.com',
    rating: 5,
    comment: 'Beautifully cooked and perfectly seasoned. A true treat!',
    date: '2026-05-20',
  },
  {
    _id: 'review-2',
    mealId: 'meal-3',
    reviewerName: 'Noah J.',
    userEmail: 'noah@example.com',
    rating: 4,
    comment: 'Delicious salmon with fresh sides. Would order again.',
    date: '2026-05-22',
  },
  {
    _id: 'review-3',
    mealId: 'meal-1',
    reviewerName: 'Mia R.',
    userEmail: 'mia@example.com',
    rating: 5,
    comment: 'Fresh, crisp, and bright. Exactly what I needed.',
    date: '2026-05-18',
  },
  {
    _id: 'review-4',
    mealId: 'meal-2',
    reviewerName: 'Liam K.',
    userEmail: 'liam@example.com',
    rating: 4,
    comment: 'Lovely roast and savory flavors. Delivery was fast.',
    date: '2026-05-19',
  },
];

export default {
  fallbackMeals,
  fallbackReviews,
};
